### ISSUE TITLE
Database architecture

### ISSUE THREAD

**Issue by islamhanafi94** [islamhanafi94/crowdFunding#2]
### **Description**

setting up the database
***

### **Task checklist**

- [x] making a comprehensive ERD
- [x] Mapping and migration
- [x] Adding all references and relations
- [x] Testing
