### ISSUE TITLE
Essential authentication

### ISSUE THREAD

**Issue by islamhanafi94** [islamhanafi94/crowdFunding#3]
### **Description**
Essential authentication
***

### **Task checklist**

- [x] Registration
- [x] Email Confirmation
- [x] Sign In
- [x] Including data validation
- [x] Testing the feature
- [x] Register and sign in forms UI
