### ISSUE TITLE
User Basic Operations

### ISSUE THREAD

**Issue by islamhanafi94** [islamhanafi94/crowdFunding#4]
### **Description**
user can view and delete his account 
***

### **Task checklist**

- [x] User can view his profile
- [x] User can view his projects
- [x] User can view his donations
- [x] User can delete his account
- [x] alert message before a user can delete his account
- [x] Testing
- [x] Task UI
