### ISSUE TITLE
Project page

### ISSUE THREAD

**Issue by islamhanafi94** [islamhanafi94/crowdFunding#5]
### **Description**
project page
***

### **Task checklist**
- [x] page UI
- [x] Project page should show the overall average rating of the project
- [x] Project page should show the project pictures in a slider- 
- [x]  Project page should show 4 other similar projects based on project tags
