### ISSUE TITLE
Home Page essential components

### ISSUE THREAD

**Issue by islamhanafi94** [islamhanafi94/crowdFunding#6]
### **Description**
.. 
***

### **Task checklist**
- [x] Nice page layout
- [x] Nav Bar
- [x] A slider to show the highest five rated running projects to encourage users to donate
- [x] List of the latest 5 projects
- [x] List of latest 5 featured projects (which are selected by the admin)
- [x] A list of the categories. User can open each category to view its projects
- [x] - Search bar that enables users to search projects by title or tag
