### ISSUE TITLE
Project Basic operations

### ISSUE THREAD

**Issue by islamhanafi94** [islamhanafi94/crowdFunding#7]
### **Description**
user can view and delete his account 
***

### **Task checklist**
- [x] User can add project
- [x] User can list/ view all  project
- [x] User can view any project and donate
- [x]  Users can rate project
- [x] Project page should show the overall average rating of the project
- [x] User can cancel his own project if the donations are less than
25% of the target
- [x] User can report Project or Comment
